package httpapi

import (
	"context"
	"log/slog"
	"net/http"
	"time"
)

// RequestID generates a new ID for every request, stores it in the request
// context and returns it through the X-Request-ID response header.
//
// Incoming client-provided request IDs are deliberately ignored during the
// MVP so logs always use identifiers generated by TimeTrap.
func RequestID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(
		responseWriter http.ResponseWriter,
		request *http.Request,
	) {
		requestID := newRequestID()

		contextWithRequestID := context.WithValue(
			request.Context(),
			requestIDKey,
			requestID,
		)

		responseWriter.Header().Set("X-Request-ID", requestID)

		next.ServeHTTP(
			responseWriter,
			request.WithContext(contextWithRequestID),
		)
	})
}

// RequestLogger records one structured log entry after each request.
//
// Request bodies are intentionally not logged because future scenarios may
// contain sensitive architectural information.
func RequestLogger(logger *slog.Logger) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(
			responseWriter http.ResponseWriter,
			request *http.Request,
		) {
			startedAt := time.Now()

			statusWriter := &statusResponseWriter{
				ResponseWriter: responseWriter,
			}

			next.ServeHTTP(statusWriter, request)

			logger.Info(
				"HTTP request",
				"request_id",
				requestIDFromContext(request.Context()),
				"method",
				request.Method,
				"path",
				request.URL.Path,
				"status",
				statusWriter.StatusCode(),
				"duration_ms",
				time.Since(startedAt).Milliseconds(),
				"remote_addr",
				request.RemoteAddr,
			)
		})
	}
}

// Recovery prevents a panic in one handler from terminating the API process.
//
// Panic details are logged internally but are never included in the response.
func Recovery(logger *slog.Logger) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(
			responseWriter http.ResponseWriter,
			request *http.Request,
		) {
			defer func() {
				recoveredValue := recover()
				if recoveredValue == nil {
					return
				}

				requestID := requestIDFromContext(request.Context())

				logger.Error(
					"HTTP handler panic",
					"request_id",
					requestID,
					"panic",
					recoveredValue,
				)

				if err := writeError(
					responseWriter,
					request,
					http.StatusInternalServerError,
					ErrorCodeInternal,
					"An unexpected error occurred.",
					nil,
				); err != nil {
					logger.Error(
						"Failed to write panic response",
						"request_id",
						requestID,
						"error",
						err,
					)
				}
			}()

			next.ServeHTTP(responseWriter, request)
		})
	}
}

// statusResponseWriter records the HTTP status code selected by a handler.
type statusResponseWriter struct {
	http.ResponseWriter
	statusCode  int
	wroteHeader bool
}

// WriteHeader records the first status code and forwards it to the underlying
// response writer. Later WriteHeader calls are ignored.
func (responseWriter *statusResponseWriter) WriteHeader(statusCode int) {
	if responseWriter.wroteHeader {
		return
	}

	responseWriter.statusCode = statusCode
	responseWriter.wroteHeader = true
	responseWriter.ResponseWriter.WriteHeader(statusCode)
}

// Write records an implicit 200 OK before forwarding the body.
func (responseWriter *statusResponseWriter) Write(body []byte) (int, error) {
	if !responseWriter.wroteHeader {
		responseWriter.WriteHeader(http.StatusOK)
	}

	return responseWriter.ResponseWriter.Write(body)
}

// StatusCode returns the recorded status or 200 when a handler writes nothing.
func (responseWriter *statusResponseWriter) StatusCode() int {
	if !responseWriter.wroteHeader {
		return http.StatusOK
	}

	return responseWriter.statusCode
}
